version: '3.8'

services:
  # This file is used ONLY for building and pushing the release images to the registry.
  # Usage: docker compose -f docker-compose.release.yml build
  # Usage: docker compose -f docker-compose.release.yml push

  yads-api:
    build:
      context: .
      target: prod
    image: registry.example.com/apps/yads/yads:latest

  yads-worker:
    build:
      context: .
      target: prod
    image: registry.example.com/apps/yads/yads:latest
