server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: yads-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: yads-api
          __path__: /app/logs/yads-api.log

  - job_name: yads-worker
    static_configs:
      - targets:
          - localhost
        labels:
          job: yads-worker
          __path__: /app/logs/yads-worker.log
